### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by voodoods** [voodoods/webpack-boilerplate#33]
Upgrade all dependencies and devDependencies referenced in the [`package.json`](https://github.com/voodoods/webpack-boilerplate/blob/master/package.json) to the latest possible version without breaking the current setup. The goal is to get rid of all current security vulnerabilities reported by dependabot: https://github.com/voodoods/webpack-boilerplate/network/alerts

<img width="971" alt="Bildschirmfoto 2020-10-04 um 20 21 07" src="https://user-images.githubusercontent.com/1707307/95023779-2f5a6a80-067f-11eb-9c97-aa36923f860e.png">

If a package requires changes in the current setup to work, please add a comment with a short explanation and I'll create a separate issue.

**Comment by erkska** [comment]
Hey! I would like to update these dependencies.

**Comment by sennahLessert** [comment]
i'll try it
