### ISSUE TITLE
Enable environment based config

### ISSUE THREAD

**Issue by voodoods** [voodoods/webpack-boilerplate#34]
Currently the available webpack configurations `prod` and `dev` are hardwired with the corresponding script commands `start` and `build`, see also [`package.json`](https://github.com/voodoods/webpack-boilerplate/blob/master/package.json#L7-L8).

It would be nice to have webpack pick the correct configuration based on an actual environment variable that is set with the given script commands. You can use `NODE_ENV` or whatever you feel is most convenient for the current setup.

**Comment by Fedelaus** [comment]
Addressed this @ https://github.com/voodoods/webpack-boilerplate/pull/35
