### ISSUE TITLE
Add a CONTRIBUTING.md

### ISSUE THREAD

**Issue by voodoods** [voodoods/webpack-boilerplate#4]
**Description:**

Add a `CONTRIBUTING.md` to this repository. You can find a good example for Open Source contribution guidelines at: https://opensource.com/life/16/3/contributor-guidelines-template-and-tips

**Comment by mddarmawan** [comment]
I will do this @voodoods

**Comment by voodoods** [comment]
solved by https://github.com/voodoods/webpack-boilerplate/pull/10
